### ISSUE TITLE
traceback error line 50 and 71

### ISSUE THREAD

**Issue by azartheen** [tamilspyboysofficial/Pollscammer#1]
Traceback (most recent call last):
  File "Pollscammer.py", line 71, in <module>
    code_statement(user_input, count)
  File "Pollscammer.py", line 50, in code_statement
    user_input = subprocess.check_output("torsocks " + user_input_first, shell=True, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'torsocks curl 'https://www.polltab.com/api/poll/rBH0zdHgOD/vote' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://www.polltab.com/rBH0zdHgOD' -H 'Content-Type: application/json' -H 'Origin: https://www.polltab.com' -H 'Connection: keep-alive' -H 'Cookie: _ga=GA1.2.1309898164.1586983096; _gid=GA1.2.1202595744.1586983096; __gads=ID=2c9c4f40610686c2:T=1586983098:S=ALNI_MZ54pFI2Wv67ZKjbUXbRsMd9Z2Rbw; 3ZP_VawhYA=iv; Nl_vvgdSln=iv' --data '{"choiceIds":["5e9888c223151b2824d2694a"]}'' returned non-zero exit status 127.

**Comment by azartheen** [comment]
curl 'https://www.polltab.com/api/poll/3ZP_VawhYA/vote' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://www.polltab.com/3ZP_VawhYA' -H 'Content-Type: application/json' -H 'Origin: https://www.polltab.com' -H 'DNT: 1' -H 'Connection: keep-alive' --data '{"choiceIds":["5e9687120e696c6121b84f42"]}'

**Comment by azartheen** [comment]
Need help after i paste the curl and mention no of count it will be show traceback error 

THANKS IN ADVANCE

**Comment by X1ucifer** [comment]
Just rerun the script its gonna be fine

**Comment by X1ucifer** [comment]
rerun the script


we will update the script soon as possible thank you
